# This workflow builds a Java Spring Boot project with Maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 (since your pom.xml uses Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build project using Maven from the correct path
      - name: Build with Maven
        run: mvn -f backend-springboot/pom.xml clean install

      # Step 4: (Optional) Update dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
